# Metrics
Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

# Naming
Naming/PredicateName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false

# Layout
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false

# Style
Style/NumericPredicate:
  Enabled: true
  EnforcedStyle: comparison
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/HashSyntax:
  Enabled: true
Style/IfUnlessModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/Next:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# Lint
Lint/Loop:
  Enabled: false
